# Generated by Django 4.1.7 on 2023-03-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(error_messages={'unique': 'This Email ID Already Exists'}, max_length=60, null=True, unique=True),
        ),
    ]
