# Generated by Django 4.1.7 on 2023-04-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_studentdetails_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='email',
            field=models.EmailField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='fname',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='lname',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='password',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='phone',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
