# Generated by Django 4.2 on 2023-11-16 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cnfrm_passw',
        ),
    ]
