# Generated by Django 4.1.7 on 2023-10-14 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=10)),
                ('salary', models.IntegerField()),
                ('qualification', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Husband',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_name', models.CharField(max_length=60)),
                ('gender', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('gender', models.CharField(max_length=20)),
                ('salary', models.IntegerField()),
                ('property', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=10)),
                ('fees', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('parents_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app1.parents')),
                ('school', models.CharField(max_length=100)),
                ('cname', models.CharField(max_length=60)),
            ],
            bases=('app1.parents',),
        ),
        migrations.CreateModel(
            name='Wife',
            fields=[
                ('husband_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app1.husband')),
                ('w_name', models.CharField(max_length=60)),
                ('child_name', models.CharField(max_length=60)),
            ],
            bases=('app1.husband',),
        ),
    ]
