# Generated by Django 4.1.7 on 2023-03-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(db_column='student_email', error_messages={'blank': 'Cant be blank', 'unique': 'This Email ID Already Exists'}, max_length=60, null=True, unique=True),
        ),
    ]
