# Generated by Django 4.1.7 on 2023-09-27 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('city', models.CharField(default=None, max_length=50)),
            ],
        ),
    ]
