# Generated by Django 4.2.2 on 2023-10-03 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_rename_stu_id_student_emp_id_remove_student_result_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Employee2',
        ),
    ]
