# Generated by Django 4.1.7 on 2023-10-20 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_oto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmarksheet',
            name='student_detail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_oto.studentdetail'),
        ),
    ]
