# Generated by Django 4.1.7 on 2023-10-22 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_oto', '0007_category_product_delete_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='course_name',
            new_name='cat_name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='duration',
        ),
    ]
