# Generated by Django 4.1.7 on 2023-05-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimg',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
